version: '3.8'

services:
  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2022-CU15-ubuntu-22.04
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - mssql_data:/var/opt/mssql
      - ./restore-db.sh:/usr/src/app/restore-db.sh
    entrypoint: /bin/bash -c "/usr/src/app/restore-db.sh & /opt/mssql/bin/sqlservr"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -C -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    container_name: app
    build: .
    ports:
      - "8501:8501"
    environment:
      - DB_SERVER=host.docker.internal,1433
      - DB_DATABASE=AdventureWorks2019
      - DB_UID=sa
      - DB_PWD=YourStrong!Passw0rd
    depends_on:
      database:
        condition: service_healthy
    restart: always

volumes:
  mssql_data:
    driver: local