name: Test Docker Compose

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Docker Compose
        run: docker-compose up --build --wait

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
